[package]
authors = ["The Tor Project"]
name = "tor_rust"
version = "0.1.0"

[lib]
name = "tor_rust"
path = "lib.rs"
crate_type = ["staticlib"]

[dependencies.tor_util]
path = "../tor_util"

[dependencies.protover]
path = "../protover"

[features]
# We have to define a feature here because doctests don't get cfg(test),
# and we need to disable some C dependencies when running the doctests
# because of the various linker issues.  See
# https://github.com/rust-lang/rust/issues/45599
test_linking_hack = []
