[workspace]
members = [
    "crypto",
    "external",
    "protover",
    "smartlist",
    "tor_allocate",
    "tor_log",
    "tor_rust",
    "tor_util",
]

[profile.release]
debug = true
panic = "abort"
